# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b68e4f90b7688e26fe37d7c8013e5536850cd9ff82c5d4688d705572638732cd8a7705a3eb0acc4ea07b879f7ce5f277ba4f0a0735883d300dde576f6618f5c0

test:
  secret_key_base: 4294a345c65e160ce4295cfce0a991ce5ec3cebcf280b96bc4ce687410631a2795c8b967c29b039560de5ba1d8dc115aebe2dc389a43081393920e27b0663abd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
